# roblox+testez: описание глобалей TestEZ лежит в testez.yml рядом с этим файлом
std = "roblox+testez"

[rules]
global_usage = "warn"
shadowing = "warn"
unused_variable = "warn"
undefined_variable = "deny"
incorrect_standard_library_use = "deny"
